In [575]:
import numpy as np
import pandas as pd

In [576]:
db = pd.read_csv('/content/sheet1.csv')
db['q'].fillna(db['q'].mean(), inplace=True)
db

id           a       b            c       d     e        f           g  \
0    1  15-01-2021  1.5570   27337.8060   17558  4.88   424741   424745.88   
1    2  24-07-2019  1.2616    1553.0296    1231  5.64    21688    21693.64   
2    3  09-08-2020  1.8000    4563.0000    2535  6.15    57690    57696.15   
3    4  12-06-2019  1.2996    2117.0484    1629  5.76    27800    27805.76   
4    5  02-06-2021  2.4762  231408.3186   93453  4.26  4175116  4175120.26   
..  ..         ...     ...          ...     ...   ...      ...         ...   
64  65  30-06-2021  2.3033  245207.0147  106459  4.16  4449518  4449522.16   
65  66  20-08-2021  1.8174  584179.6038  321437  5.73  7148710  7148715.73   
66  67  24-09-2021  2.1319  652107.7039  305881  6.08  7768271  7768277.08   
67  68  28-12-2020  1.6154   23749.6108   14702  4.83   373796   373800.83   
68  69  20-09-2021  2.3670  232531.7130   98239  3.78  4509271  4509274.78   

        h     i  ...     n      o      p    q    r     s       t           u  \
0     101   105  ...   443    940  30.63  0.0  0.0   356   27337   1530.0084   
1       1     4  ...    14     31  27.86  0.0  0.0     8    1553     60.2926   
2      27    30  ...   162    232  25.98  0.0  0.0   103    4563    230.7383   
3       9     3  ...    34     64  26.28  0.0  0.0    19    2117    100.3671   
4     464   417  ...  2325   9126  33.26  0.0  0.0  1997  231404  17511.5046   
..    ...   ...  ...   ...    ...    ...  ...  ...   ...     ...         ...   
64    825   423  ...  2978  11819  38.56  0.0  0.0  2269  245204  21847.0122   
65  11582  1405  ...  4959  58446  45.70  1.0  2.0  3785  584188  64133.8247   
66   4741  1055  ...  4804  56677  47.81  1.0  0.0  3284  652105  54463.2654   
67    110    74  ...   487   1106  30.22  0.0  0.0   423   23750   1414.7931   
68    425   453  ...  2933   9536  37.28  0.0  0.0  1997  232530  17900.4225   

           v   target  
0   00:03:21    5.785  
1   00:02:19    0.826  
2   00:03:02    1.201  
3   00:02:50    0.963  
4   00:04:32   59.635  
..       ...      ...  
64  00:05:20  125.014  
65  00:06:35  317.818  
66  00:05:00  397.066  
67  00:03:34    6.017  
68  00:04:37  107.846  

[69 rows x 24 columns]

In [577]:
db.columns

Index(['id', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'target'],
      dtype='object')

In [578]:
db.drop(['a','j','r','e','q','id'], axis = 1, inplace=True)

In [579]:
db2 = db.target

In [580]:
db.drop('target', axis = 1, inplace=True)
db

b            c       d        f           g      h     i      k    l  \
0   1.5570   27337.8060   17558   424741   424745.88    101   105  35.51   20   
1   1.2616    1553.0296    1231    21688    21693.64      1     4  33.50    1   
2   1.8000    4563.0000    2535    57690    57696.15     27    30  32.13   11   
3   1.2996    2117.0484    1629    27800    27805.76      9     3  32.04    0   
4   2.4762  231408.3186   93453  4175116  4175120.26    464   417  37.52  157   
..     ...          ...     ...      ...         ...    ...   ...    ...  ...   
64  2.3033  245207.0147  106459  4449518  4449522.16    825   423  42.72  171   
65  1.8174  584179.6038  321437  7148710  7148715.73  11582  1405  51.43  404   
66  2.1319  652107.7039  305881  7768271  7768277.08   4741  1055  53.89  521   
67  1.6154   23749.6108   14702   373796   373800.83    110    74  35.05   35   
68  2.3670  232531.7130   98239  4509271  4509274.78    425   453  41.06  163   

       m     n      o      p     s       t           u         v  
0     87   443    940  30.63   356   27337   1530.0084  00:03:21  
1      6    14     31  27.86     8    1553     60.2926  00:02:19  
2     59   162    232  25.98   103    4563    230.7383  00:03:02  
3     15    34     64  26.28    19    2117    100.3671  00:02:50  
4    328  2325   9126  33.26  1997  231404  17511.5046  00:04:32  
..   ...   ...    ...    ...   ...     ...         ...       ...  
64   709  2978  11819  38.56  2269  245204  21847.0122  00:05:20  
65  1174  4959  58446  45.70  3785  584188  64133.8247  00:06:35  
66  1520  4804  56677  47.81  3284  652105  54463.2654  00:05:00  
67    64   487   1106  30.22   423   23750   1414.7931  00:03:34  
68   936  2933   9536  37.28  1997  232530  17900.4225  00:04:37  

[69 rows x 17 columns]

In [581]:
for i in range(69):
  minutes = db.v[i][4]
  minutes_num = int(minutes)
  db.loc[i, 'v'] = minutes_num

In [582]:
db

b            c       d        f           g      h     i      k    l  \
0   1.5570   27337.8060   17558   424741   424745.88    101   105  35.51   20   
1   1.2616    1553.0296    1231    21688    21693.64      1     4  33.50    1   
2   1.8000    4563.0000    2535    57690    57696.15     27    30  32.13   11   
3   1.2996    2117.0484    1629    27800    27805.76      9     3  32.04    0   
4   2.4762  231408.3186   93453  4175116  4175120.26    464   417  37.52  157   
..     ...          ...     ...      ...         ...    ...   ...    ...  ...   
64  2.3033  245207.0147  106459  4449518  4449522.16    825   423  42.72  171   
65  1.8174  584179.6038  321437  7148710  7148715.73  11582  1405  51.43  404   
66  2.1319  652107.7039  305881  7768271  7768277.08   4741  1055  53.89  521   
67  1.6154   23749.6108   14702   373796   373800.83    110    74  35.05   35   
68  2.3670  232531.7130   98239  4509271  4509274.78    425   453  41.06  163   

       m     n      o      p     s       t           u  v  
0     87   443    940  30.63   356   27337   1530.0084  3  
1      6    14     31  27.86     8    1553     60.2926  2  
2     59   162    232  25.98   103    4563    230.7383  3  
3     15    34     64  26.28    19    2117    100.3671  2  
4    328  2325   9126  33.26  1997  231404  17511.5046  4  
..   ...   ...    ...    ...   ...     ...         ... ..  
64   709  2978  11819  38.56  2269  245204  21847.0122  5  
65  1174  4959  58446  45.70  3785  584188  64133.8247  6  
66  1520  4804  56677  47.81  3284  652105  54463.2654  5  
67    64   487   1106  30.22   423   23750   1414.7931  3  
68   936  2933   9536  37.28  1997  232530  17900.4225  4  

[69 rows x 17 columns]

In [583]:
db2

0       5.785
1       0.826
2       1.201
3       0.963
4      59.635
       ...   
64    125.014
65    317.818
66    397.066
67      6.017
68    107.846
Name: target, Length: 69, dtype: float64

In [584]:
X_train = np.array(db)
X_train.shape

(69, 17)

In [585]:
Y_train = np.array(db2)
Y_train

array([5.78500e+00, 8.26000e-01, 1.20100e+00, 9.63000e-01, 5.96350e+01,
       3.22000e-01, 3.98500e+00, 2.55710e+01, 5.08280e+01, 1.54300e+00,
       9.92000e-01, 1.07500e+00, 1.77200e+00, 1.22600e+00, 1.21000e-01,
       6.42620e+01, 6.56370e+01, 3.49500e+00, 0.00000e+00, 2.47000e+00,
       1.50000e-01, 7.96730e+01, 0.00000e+00, 9.29600e+00, 7.20000e-02,
       2.40800e+00, 6.66100e+00, 0.00000e+00, 2.50000e-01, 2.47300e+00,
       2.14000e-01, 4.05500e+00, 5.36100e+00, 0.00000e+00, 1.16100e+00,
       4.28700e+00, 7.60000e-02, 1.01652e+02, 1.17100e+00, 2.38290e+01,
       5.38200e+00, 3.33450e+01, 1.15600e+00, 1.09000e-01, 7.97120e+01,
       1.82000e-01, 6.66100e+00, 4.60700e+00, 1.33400e+00, 0.00000e+00,
       2.51000e-01, 1.07340e+01, 5.50310e+01, 2.16000e-01, 7.02700e+00,
       3.67000e-01, 3.91000e+00, 0.00000e+00, 5.99300e+00, 1.47525e+02,
       0.00000e+00, 5.82600e+00, 1.31000e-01, 0.00000e+00, 1.25014e+02,
       3.17818e+02, 3.97066e+02, 6.01700e+00, 1.07846e+02])

In [586]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)


In [587]:

from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor(loss='absolute_error',learning_rate=0.01,n_estimators=500,max_depth = 1, random_state = 82,max_features=9)
model.fit(X_train,Y_train)

GradientBoostingRegressor(learning_rate=0.01, loss='absolute_error',
                          max_depth=1, max_features=9, n_estimators=500,
                          random_state=82)

In [588]:
# import matplotlib.pyplot as plt
# plt.scatter(X[0:69][1],Y[])

In [589]:
df_pred = pd.read_csv('sheet2.csv')
df_pred['q'].fillna(df_pred['q'].mean(), inplace=True)


In [590]:
df_pred

id           a       b           c      d     e       f          g  \
0        1  12-10-2020  1.6106   6683.9900   4150  5.86   82477   82482.86   
1        2  04-02-2021  1.6255  24065.5275  14805  4.94  360696  360700.94   
2        3  08-10-2019  1.5132   1091.0172    721  6.39   13192   13198.39   
3        4  01-12-2019  1.4206    608.0168    428  5.97    8810    8815.97   
4        5  04-09-2020  1.6092  15979.3560   9930  6.89  182250  182256.89   
...    ...         ...     ...         ...    ...   ...     ...        ...   
1059  1060  04-09-2019  1.3789    654.9775    475  6.30    8768    8774.30   
1060  1061  24-02-2019  1.6983  13941.3447   8209  8.24  125023  125031.24   
1061  1062  22-09-2020  1.5895  27107.3330  17054  5.68  348990  348995.68   
1062  1063  25-03-2019  1.4379   5484.1506   3814  8.21   51635   51643.21   
1063  1064  20-10-2020  1.5900  10365.2100   6519  5.69  144428  144433.69   

         h    i  ...    m    n     o      p    q    r    s      t          u  \
0       27   41  ...   46  147   242  27.96  0.0  0.0  101   6684   361.8757   
1       83   81  ...  103  334  1048  31.87  0.0  0.0  231  24066  1472.3777   
2        0    3  ...    4   15    13  25.78  0.0  0.0   11   1091    39.3224   
3        2    0  ...    5   14     9  26.03  0.0  0.0    9    608    21.0277   
4       78   55  ...   69  346   997  28.86  0.0  0.0  277  15979   854.6027   
...    ...  ...  ...  ...  ...   ...    ...  ...  ...  ...    ...        ...   
1059     2    3  ...    5    4    15  26.26  0.0  0.0   -1    655    23.2315   
1060  1094   19  ...   30  185   650  14.24  3.0  4.0  155  13941   776.5155   
1061   145  110  ...   94  586  1458  30.92  0.0  0.0  492  27108  1634.9794   
1062    12   17  ...    7   82   137  24.42  0.0  0.0   75   5484   199.8006   
1063    40   33  ...   60  259   480  30.45  0.0  0.0  199  10365   631.9848   

             v  
0     00:03:14  
1     00:03:40  
2     00:02:09  
3     00:02:04  
4     00:03:12  
...        ...  
1059  00:02:07  
1060  00:03:20  
1061  00:03:37  
1062  00:02:11  
1063  00:03:39  

[1064 rows x 23 columns]

In [591]:
df_pred.drop(['a','j','r','e','q'], axis = 1, inplace=True)


In [592]:
df_pred.drop('id', axis = 1, inplace=True)


In [593]:
for i in range(1064):
  minutes = df_pred.v[i][4]
  minutes_num = int(minutes)
  df_pred.loc[i, 'v'] = minutes_num


In [594]:
X_test = np.array(df_pred)

In [595]:
X_test.shape

(1064, 17)

In [596]:
X_test

array([[1.6106, 6683.99, 4150, ..., 6684, 361.8757, 3],
       [1.6255, 24065.5275, 14805, ..., 24066, 1472.3777, 3],
       [1.5132, 1091.0172, 721, ..., 1091, 39.3224, 2],
       ...,
       [1.5895, 27107.333, 17054, ..., 27108, 1634.9794, 3],
       [1.4379, 5484.1506, 3814, ..., 5484, 199.8006, 2],
       [1.59, 10365.21, 6519, ..., 10365, 631.9848, 3]], dtype=object)

In [597]:
df_impute = pd.DataFrame(X_test)

In [598]:
# from sklearn.impute import KNNImputer
# imputer = KNNImputer(n_neighbors=5)
# df_imputed = imputer.fit_transform(df_impute)

# X_test = df_imputed

In [599]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_test)
X_test = scaler.transform(X_test)


In [600]:
prediction = model.predict(X_test)

In [601]:
prediction

array([ 3.44540582,  8.74375782,  1.26802384, ..., 20.79889368,
        3.44540582,  3.44540582])

In [602]:
pred_df = pd.DataFrame(prediction)

In [603]:
l = []
i = 1
while i<=1064:
  l.append(i)
  i+=1

In [604]:
pred_df.insert(0, "id",l, True)

In [605]:
pred_df.columns = ['id', 'target']

In [606]:
pred_df

id     target
0        1   3.445406
1        2   8.743758
2        3   1.268024
3        4   1.120523
4        5   5.217033
...    ...        ...
1059  1060   1.120523
1060  1061   6.676905
1061  1062  20.798894
1062  1063   3.445406
1063  1064   3.445406

[1064 rows x 2 columns]

In [607]:
pred_df.to_csv('Result.csv')