In [2]:
import pandas as pd
import numpy as np

In [3]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
# sample_result = pd.read_csv('sample_submission.csv')

In [4]:
uni_df_train = list(train.var13.unique())
uni_df_train.remove(np.nan)
df_count = train.groupby('var13')
for i in uni_df_train:
  # print(i)
  df = df_count.get_group(i)
  count = df.shape[0]
  train['var13'].replace(i,count,inplace=True)


In [ ]:
# uni_df_train3 = list(train.var1.unique())
# df_count_3 = train.groupby('var1')
# print(uni_df_train3)
# for i in uni_df_train3:
#   df_3 = df_count_3.get_group(i)
#   count_3 = df_3.shape[0]
#   train.var1.replace(i,count_3, inplace=True)

# train.drop('var1',axis=1,inplace=True)

In [5]:
uni_df_train_2 = list(train.var15.unique())
df_count_2 = train.groupby('var15')
print(uni_df_train_2)
for i in uni_df_train_2:
  # print(i)
  df_2 = df_count_2.get_group(i)
  count_2 = df_2.shape[0]
  train['var15'].replace(i,count_2,inplace=True)

train

['A', 'I', 'B', 'L', 'K', 'D', 'H', 'J', 'E', 'G', 'F', 'C']


ID  var1  var2  var3  var4       var5         var6         var7  \
0            0  2013    12     8    17  11.000000 -1144.351458   500.000000   
1            1  2013     5    16     7  17.000000   -51.596321  1698.073461   
2            2  2014     6    26     7 -12.059049    45.000000   900.000000   
3            3  2016     5    14     7   2.000000    21.000000   300.000000   
4            4  2016    10     2    11   2.000000    46.861528  1884.153559   
...        ...   ...   ...   ...   ...        ...          ...          ...   
306863  306863  2015     4    11     5  17.000000    66.000000  2674.314692   
306864  306864  2016     1     3     2  23.000000    67.440307  5500.000000   
306865  306865  2017     1    11     9  12.000000    66.000000  2695.833408   
306866  306866  2016    12     5     6   9.000000    63.000000  2049.430777   
306867  306867  2016     6     7    13   3.000000    23.000000   900.000000   

              var8       var9        var10       var11     var12    var13  \
0        45.000000   6.400000  1067.590514  -10.800000 -6.253469  18430.0   
1        20.458846  19.900000  1016.200000    2.947184  0.000000  21806.0   
2        31.000000  24.600000   997.900000   22.300000  0.000000  18430.0   
3        25.723403  12.600000          NaN    9.800000  0.700000  17717.0   
4        42.000000   6.003678  1010.000000  158.531366  0.000000  31373.0   
...            ...        ...          ...         ...       ...      ...   
306863   27.000000  12.700000  1010.800000  116.883148  0.000000  31373.0   
306864    2.000000  -3.200000  1011.900000   -7.000000  0.000000  18430.0   
306865    6.000000   9.703111  1016.000000 -147.811549  0.176683  24073.0   
306866    4.665397   2.800000  1014.700000   -7.690267  0.000000  24903.0   
306867  163.829802  24.700000   598.497195  -28.811246  0.000000  14154.0   

           var14  var15      target  
0       3.700000  25605   32.000000  
1       1.000000  24326   89.000000  
2      -2.990469  25605  154.592918  
3       1.045986  26069   24.000000  
4       1.800000  26268  196.000000  
...          ...    ...         ...  
306863  0.500000  26062  211.039870  
306864  1.200000  25149  392.000000  
306865  1.553953  26062  245.835549  
306866  2.100000  26069  158.000000  
306867  2.200000  24362   91.000000  

[306868 rows x 17 columns]

In [ ]:
from sklearn.impute import KNNImputer
impute = KNNImputer(n_neighbors=2)
train = impute.fit_transform(train)
# train = pd.read_csv('train_n.csv')
# train

In [ ]:
train = pd.DataFrame(train)
train.columns = ['ID','var1','var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8', 'var9', 'var10', 'var11', 'var12', 'var13','var14','var15','target']

In [ ]:
# cols = ['ID','var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8', 'var9', 'var10', 'var11', 'var12', 'var13','var14','var15','target']
# train.columns = cols
# train

In [ ]:
# train.to_csv('train_n.csv',index=False)

In [ ]:
y_train = train.target
x_train = train.drop('target',axis=1)
# cols = x_train.columns

In [ ]:
x_train.drop('ID',axis=1,inplace=True)

In [ ]:
# from sklearn.preprocessing import StandardScaler
# scale = StandardScaler()
# x_train_scale = pd.DataFrame(scale.fit_transform(x_train))
# x_train_scale.columns = cols
# x_train_scale.drop('ID',axis=1,inplace=True)


In [ ]:
# x = np.nan
# r = 6
# l = [1,2,3,4,5,6,x,23,8]
# l.remove(6)
# l

In [ ]:
test

ID  var1  var2  var3  var4   var5   var6    var7   var8  var9  \
0          0  2014     2    12    11   23.0   50.0  1300.0    9.0   2.4   
1          1  2014     7    29    23    2.0   16.0   800.0  155.0  23.4   
2          2  2013     4    18    11    3.0   10.0   300.0   91.0  12.6   
3          3  2014     1    27     9   81.0   98.0  3100.0    1.0  -1.4   
4          4  2016     6    29    16    2.0   20.0   800.0  176.0  28.4   
...      ...   ...   ...   ...   ...    ...    ...     ...    ...   ...   
76712  76712  2014     1    23    18  139.0  136.0  3400.0    1.0  -1.9   
76713  76713  2013     5    14     9    8.0   22.0   300.0   80.0  25.8   
76714  76714  2014     6    19     6    2.0   65.0   700.0   25.0  23.5   
76715  76715  2017     1     1     6    9.0  104.0  7200.0    3.0  -4.5   
76716  76716  2016     3    16     8   26.0  120.0  3500.0   12.0   4.0   

        var10  var11  var12 var13  var14 var15  
0      1027.6  -15.2    0.0     C    2.4     E  
1       999.5   22.2    6.7     I    0.0     H  
2      1016.0  -15.2    0.0     E    2.1     F  
3      1011.7   -7.7    0.0     E    2.0     K  
4       999.4   19.9    0.0     P    2.0     D  
...       ...    ...    ...   ...    ...   ...  
76712  1008.9  -10.2    0.0     E    0.9     A  
76713  1001.3    1.1    0.0     E    2.0     F  
76714   995.7   13.4    0.0     D    0.6     B  
76715  1021.5   -5.5    0.0     B    1.2     A  
76716  1014.3   -0.6    0.0     E    1.0     H  

[76717 rows x 16 columns]

In [ ]:
# test.columns = ['ID','var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8', 'var9', 'var10', 'var11', 'var12', 'var13','var14','var15']
test

ID  var1  var2  var3  var4   var5   var6    var7   var8  var9  \
0          0  2014     2    12    11   23.0   50.0  1300.0    9.0   2.4   
1          1  2014     7    29    23    2.0   16.0   800.0  155.0  23.4   
2          2  2013     4    18    11    3.0   10.0   300.0   91.0  12.6   
3          3  2014     1    27     9   81.0   98.0  3100.0    1.0  -1.4   
4          4  2016     6    29    16    2.0   20.0   800.0  176.0  28.4   
...      ...   ...   ...   ...   ...    ...    ...     ...    ...   ...   
76712  76712  2014     1    23    18  139.0  136.0  3400.0    1.0  -1.9   
76713  76713  2013     5    14     9    8.0   22.0   300.0   80.0  25.8   
76714  76714  2014     6    19     6    2.0   65.0   700.0   25.0  23.5   
76715  76715  2017     1     1     6    9.0  104.0  7200.0    3.0  -4.5   
76716  76716  2016     3    16     8   26.0  120.0  3500.0   12.0   4.0   

        var10  var11  var12 var13  var14 var15  
0      1027.6  -15.2    0.0     C    2.4     E  
1       999.5   22.2    6.7     I    0.0     H  
2      1016.0  -15.2    0.0     E    2.1     F  
3      1011.7   -7.7    0.0     E    2.0     K  
4       999.4   19.9    0.0     P    2.0     D  
...       ...    ...    ...   ...    ...   ...  
76712  1008.9  -10.2    0.0     E    0.9     A  
76713  1001.3    1.1    0.0     E    2.0     F  
76714   995.7   13.4    0.0     D    0.6     B  
76715  1021.5   -5.5    0.0     B    1.2     A  
76716  1014.3   -0.6    0.0     E    1.0     H  

[76717 rows x 16 columns]

In [ ]:
cols = list(test.columns)
x = np.nan

uni_df_test = list(test.var13.unique())
df_count = test.groupby('var13')
uni_df_test.pop(-5)
for i in uni_df_test:
  # print(i)
  df = df_count.get_group(i)
  count = df.shape[0]
  test['var13'].replace(i,count,inplace=True)

# uni_df_test3 = list(test.var1.unique())
# df_count_3 = test.groupby('var1')
# for i in uni_df_test3:
#   df_3 = df_count_3.get_group(i)
#   count_3 = df_3.shape[0]
#   test.var1.replace(i,count_3, inplace=True)
# test.drop('var1',axis=1,inplace=True)
# cols.remove('var1')

uni_df_test_2 =list(test.var15.unique())
df_count_2 = test.groupby('var15')
for i in uni_df_test_2:
  # print(i)
  df_2 = df_count_2.get_group(i)
  count_2 = df_2.shape[0]
  test['var15'].replace(i,count_2,inplace=True)

from sklearn.impute import KNNImputer
impute = KNNImputer(n_neighbors=2)
test = impute.fit_transform(test)
# test = pd.DataFrame(test)
# test.columns = cols

print(test)

# from sklearn.preprocessing import StandardScaler
# scale = StandardScaler()
# x_test_scale = pd.DataFrame(scale.fit_transform(test))
# x_test_scale.columns = cols
# x_test_scale.drop('ID',axis=1,inplace=True)
# x_test_scale
# y_test = x_test_scale.target


[[0.0000e+00 2.0140e+03 2.0000e+00 ... 4.4710e+03 2.4000e+00 6.3630e+03]
 [1.0000e+00 2.0140e+03 7.0000e+00 ... 3.5290e+03 0.0000e+00 6.6100e+03]
 [2.0000e+00 2.0130e+03 4.0000e+00 ... 7.9460e+03 2.1000e+00 6.5530e+03]
 ...
 [7.6714e+04 2.0140e+03 6.0000e+00 ... 5.6710e+03 6.0000e-01 6.7050e+03]
 [7.6715e+04 2.0170e+03 1.0000e+00 ... 6.2360e+03 1.2000e+00 6.2710e+03]
 [7.6716e+04 2.0160e+03 3.0000e+00 ... 7.9460e+03 1.0000e+00 6.6100e+03]]


In [ ]:
# x_test_scale.columns = ['ID','var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8', 'var9', 'var10', 'var11', 'var12', 'var13','var14','var15']

In [ ]:
x_test = pd.DataFrame(test)
x_test.columns = ['ID','var1','var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8', 'var9', 'var10', 'var11', 'var12', 'var13','var14','var15']

In [ ]:
x_test.drop('ID',axis=1,inplace=True)

In [ ]:
# from sklearn.preprocessing import PolynomialFeatures

# eq = PolynomialFeatures(degree=3)
# poly_x_train_scale = eq.fit_transform(x_train_scale)
# poly_x_test_scale = eq.fit_transform(x_test_scale)

In [ ]:
# from sklearn.linear_model import LinearRegression
# model = LinearRegression()
# model.fit(poly_x_train_scale,y_train)

In [ ]:
# pd.DataFrame(poly_x_train_scale)
# pd.DataFrame(poly_x_test_scale)

In [ ]:
# train.drop('ID',axis=1,inplace=True)
# train

In [ ]:
# x_train = np.array(train).reshape(-1,1)

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor(n_estimators=1000, learning_rate=0.03, max_depth=5, random_state=82)
model.fit(x_train,y_train)

# import numpy as np
# from keras.models import Sequential
# from keras.layers import Dense

# # Define the deep learning model
# def build_model(input_dim):
#     model = Sequential()
#     model.add(Dense(128, activation='relu', input_dim=input_dim))
#     model.add(Dense(64, activation='relu'))
#     model.add(Dense(1, activation='linear'))  # For regression tasks, use 'linear' activation

#     model.compile(optimizer='adam', loss='mean_squared_error')  # Use appropriate loss for your task

#     return model

# # Assuming x_train has shape (300000, 15) and y_train has shape (300000,)
# input_dim = x_train.shape[1]
# model = build_model(input_dim)

# # Train the model
# model.fit(x_train, y_train, epochs=20, batch_size=12)  # You can adjust epochs and batch_size


GradientBoostingRegressor(learning_rate=0.03, max_depth=5, n_estimators=1000,
                          random_state=82)

In [ ]:
x_train

var1  var2  var3  var4       var5         var6         var7  \
0       2013.0  12.0   8.0  17.0  11.000000 -1144.351458   500.000000   
1       2013.0   5.0  16.0   7.0  17.000000   -51.596321  1698.073461   
2       2014.0   6.0  26.0   7.0 -12.059049    45.000000   900.000000   
3       2016.0   5.0  14.0   7.0   2.000000    21.000000   300.000000   
4       2016.0  10.0   2.0  11.0   2.000000    46.861528  1884.153559   
...        ...   ...   ...   ...        ...          ...          ...   
306863  2015.0   4.0  11.0   5.0  17.000000    66.000000  2674.314692   
306864  2016.0   1.0   3.0   2.0  23.000000    67.440307  5500.000000   
306865  2017.0   1.0  11.0   9.0  12.000000    66.000000  2695.833408   
306866  2016.0  12.0   5.0   6.0   9.000000    63.000000  2049.430777   
306867  2016.0   6.0   7.0  13.0   3.000000    23.000000   900.000000   

              var8       var9        var10       var11     var12    var13  \
0        45.000000   6.400000  1067.590514  -10.800000 -6.253469  18430.0   
1        20.458846  19.900000  1016.200000    2.947184  0.000000  21806.0   
2        31.000000  24.600000   997.900000   22.300000  0.000000  18430.0   
3        25.723403  12.600000   727.958550    9.800000  0.700000  17717.0   
4        42.000000   6.003678  1010.000000  158.531366  0.000000  31373.0   
...            ...        ...          ...         ...       ...      ...   
306863   27.000000  12.700000  1010.800000  116.883148  0.000000  31373.0   
306864    2.000000  -3.200000  1011.900000   -7.000000  0.000000  18430.0   
306865    6.000000   9.703111  1016.000000 -147.811549  0.176683  24073.0   
306866    4.665397   2.800000  1014.700000   -7.690267  0.000000  24903.0   
306867  163.829802  24.700000   598.497195  -28.811246  0.000000  14154.0   

           var14    var15  
0       3.700000  25605.0  
1       1.000000  24326.0  
2      -2.990469  25605.0  
3       1.045986  26069.0  
4       1.800000  26268.0  
...          ...      ...  
306863  0.500000  26062.0  
306864  1.200000  25149.0  
306865  1.553953  26062.0  
306866  2.100000  26069.0  
306867  2.200000  24362.0  

[306868 rows x 15 columns]

In [ ]:
prdct = model.predict(x_test)

In [ ]:
df_prediction = pd.DataFrame(prdct)

In [ ]:
list_cols = ['Target']
df_prediction.columns = list_cols

In [ ]:
df_prediction
df_prediction.to_csv('/content/output.csv',index=True)

In [ ]:
df_prediction

Target
0       66.588060
1       86.011063
2       24.156108
3      179.565026
4       68.771970
...           ...
76712  288.436453
76713   64.114870
76714   69.246296
76715  400.115436
76716  288.779480

[76717 rows x 1 columns]

In [1]:
# import pandas as pd
# import numpy as np
# from sklearn.impute import KNNImputer
# from sklearn.ensemble import GradientBoostingRegressor
# from sklearn.model_selection import GridSearchCV
# from sklearn.preprocessing import StandardScaler, OneHotEncoder
# from sklearn.compose import ColumnTransformer

# # Load the data
# train = pd.read_csv('train.csv')
# test = pd.read_csv('test.csv')

# # Preprocess the training data
# uni_df_train_2 = list(train.var15.unique())
# df_count_2 = train.groupby('var15')
# for i in uni_df_train_2:
#     df_2 = df_count_2.get_group(i)
#     count_2 = df_2.shape[0]
#     train['var15'].replace(i, count_2, inplace=True)

# uni_df_train = list(train.var13.unique())
# uni_df_train.remove(np.nan)
# df_count = train.groupby('var13')
# for i in uni_df_train:
#     df = df_count.get_group(i)
#     count = df.shape[0]
#     train['var13'].replace(i, count, inplace=True)

# impute = KNNImputer(n_neighbors=2)
# train_filled = impute.fit_transform(train)

# # Convert the preprocessed training data to a DataFrame
# train_filled = pd.DataFrame(train_filled, columns=train.columns)

# # Separate features and target variable
# y_train = train_filled['target']
# x_train = train_filled.drop(['target', 'ID'], axis=1)

# # Preprocess the test data
# uni_df_test_2 = list(test.var15.unique())
# df_count = test.groupby('var15')
# for i in uni_df_test_2:
#     df_2 = df_count.get_group(i)
#     count_2 = df_2.shape[0]
#     test['var15'].replace(i, count_2, inplace=True)

# uni_df_test = list(test.var13.unique())
# df_count = test.groupby('var13')
# uni_df_test.remove(np.nan)
# for i in uni_df_test:
#     df = df_count.get_group(i)
#     count = df.shape[0]
#     test['var13'].replace(i, count, inplace=True)

# impute = KNNImputer(n_neighbors=2)
# test_filled = impute.fit_transform(test)

# # Convert the preprocessed test data to a DataFrame
# test_filled = pd.DataFrame(test_filled, columns=test.columns)

# # Separate features for test data
# x_test = test_filled.drop('ID', axis=1)

# # Perform feature scaling on numerical features
# numerical_features = ['var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8', 'var9', 'var10', 'var11', 'var12', 'var13', 'var14', 'var15']

# preprocessor = ColumnTransformer(
#     transformers=[
#         ('num', StandardScaler(), numerical_features),
#     ],
#     remainder='passthrough'
# )

# x_train_scaled = preprocessor.fit_transform(x_train)
# x_test_scaled = preprocessor.transform(x_test)

# # Perform hyperparameter tuning using GridSearchCV
# param_grid = {
#     'n_estimators': [100, 200, 500],
#     'learning_rate': [0.01, 0.03, 0.1],
#     'max_depth': [3, 5, 7]
# }

# model = GradientBoostingRegressor(random_state=82)

# grid_search = GridSearchCV(model, param_grid, cv=5, scoring='r2', n_jobs=-1)
# grid_search.fit(x_train_scaled, y_train)

# best_model = grid_search.best_estimator_
# best_params = grid_search.best_params_

# print("Best R2 Score:", grid_search.best_score_)
# print("Best Parameters:", best_params)

# # Make predictions on the test set
# predictions = best_model.predict(x_test_scaled)

# # Create a DataFrame to store the predictions
# output_df = pd.DataFrame({'ID': test['ID'], 'Target': predictions})

# # Save the predictions to a CSV file
# output_df.to_csv('output.csv', index=False)


KeyboardInterrupt: ignored