In [5]:
w1,w2,w3 = 0.1,0.2,0.3
Kanto = [[73,67,43],[2,3,4],] #[temperature,rainfall,humidity]
weights = [0.1,0.2,0.3] #[w1,w2,w3]

#Calculating Yields!
# result = 0
# for i,j in zip(Kanto,weights):
#     result+=i*j
# print(result)


import numpy as np
kanto = np.array(Kanto)
print(type(kanto))
weight = np.array(weights)

x = np.dot(kanto,weight)
print(x)
#Basically dot product hota h ye!
print(weight*kanto) #This is element-wise multiplication

#Numpy is very fast! As it involves direct C++ to assembly language in backend, numpy dot is 100 times faster than for loop!

<class 'numpy.ndarray'>
[33.6  2. ]
[[ 7.3 13.4 12.9]
 [ 0.2  0.6  1.2]]


In [ ]:
climate_data = np.array([[73,41,32],
                        [34,54,22],
                        [36,76,54],
                        [48,39,81]]
                        )
#That's a 2D Array  similarly we can have nD array however mostly till 3D we use!

In [ ]:
d3_array = np.array([[[43,23],
                      [23,43],

                      [56,21],
                      [92,82]]])

In [ ]:
climate_data.shape

(4, 3)

In [ ]:
d3_array.shape


(1, 4, 2)

In [ ]:
weight.dtype

dtype('float64')

This implies that the data is limited to 64 bits

In [ ]:
#Matrix Multiplication

mat1 = climate_data
mat2 = weight

#now multiplication part

np.matmul(mat1,mat2)
#this can also be written as

x = mat1 @ mat2
print(x)

[25.1 20.8 35.  36.9]


basic functions

In [ ]:
#ndim
print(climate_data.ndim)

#shape
print(climate_data.shape)

#type
print(climate_data.dtype)

2
(4, 3)
int64


Moving on with Numpy


In [7]:
tr = np.array([[3.0,4.0,4.5,3.2,5.0],[5.0,4.0,2.1,4.2,8.9]],dtype="float32")
#Get dimension
tr.ndim

2

In [8]:
#Get Shape
tr.shape

(2, 5)

In [10]:
#Get Type
tr.dtype

dtype('float32')

In [ ]:
#Get Size
tr.itemsize

4

In [ ]:
#Get Totalsize
tr.nbytes

32

Accessing/Changing specific elements, rows and columns

In [11]:
#Get a specific element [r,c]
tr[1,3]

#Works same as indexing in python starts with 0 and negative as well

4.2

Specific Row

In [13]:
tr[0:2,0:4]

array([[3. , 4. , 4.5, 3.2],
       [5. , 4. , 2.1, 4.2]], dtype=float32)

In [ ]:
tr[0]

array([3. , 4. , 4.5, 3.2, 5. ], dtype=float32)

In [ ]:
tr[0,:]

array([3. , 4. , 4.5, 3.2, 5. ], dtype=float32)

Specific Column Finder

In [ ]:
tr[:,2]

array([4.5, 2.1], dtype=float32)

In [ ]:
#Replacing elements

tr[0,3] = 4
print(tr)

[[3.  4.  4.5 4. ]
 [5.  4.  2.1 4.2]]


In [ ]:
tr[0,:]=4.1
print(tr)

[[4.1 4.1 4.1 4.1]
 [5.  4.  2.1 4.2]]


In [ ]:
array_3d  = np.array([[[23,32,43],[45,32,44]],[[31,56,82],[28,53,11]]])

print(array_3d)

[[[23 32 43]
  [45 32 44]]

 [[31 56 82]
  [28 53 11]]]


Fetching element set

In [ ]:
array_3d[0,1,1]

32

In [ ]:
array_3d[:,1,:] = [3,4,2]

print(array_3d)

[[[23 32 43]
  [ 3  4  2]]

 [[31 56 82]
  [ 3  4  2]]]


Pre-built Matrices

In [ ]:
#All 0s matrix

np.zeros((2,3)) #zeroes((rows,columns))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#All 1s matrix

np.ones((4,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
arr = np.ones((8,8))
arr
arr[1:7,1:7]=0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
#Any other numbers

np.full((2,2),11)   #Takes in 2 or 3 parameters, basically full((rows,columns,...),number that needs to be there, dtype=?(if any))


array([[11, 11],
       [11, 11]])

In [ ]:
#Any other number (full_like)

np.full_like(array_3d, 4)

array([[[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]]])

In [ ]:
#Random numbers
import random
print(np.random.rand(4,2))  #(rows,columns)
print()
print(np.random.random_sample(array_3d.shape)) #Takes shape like a premade sample

[[0.90367784 0.99232957]
 [0.03460092 0.92251782]
 [0.33209911 0.35680428]
 [0.40529926 0.9477893 ]]

[[[0.01063916 0.13706894 0.57011492]
  [0.49848941 0.27109095 0.16717566]]

 [[0.72325222 0.87762449 0.45330106]
  [0.93804291 0.89682206 0.63094523]]]


Randint

In [ ]:
np.random.randint(2,5,(2,2))  #(limit_min,Limit_max, size or shape)

array([[3, 4],
       [3, 3]])

In [ ]:
r1 = np.repeat(climate_data,3,axis=0)
print(climate_data.ndim)
print(r1)

2
[[73 41 32]
 [73 41 32]
 [73 41 32]
 [34 54 22]
 [34 54 22]
 [34 54 22]
 [36 76 54]
 [36 76 54]
 [36 76 54]
 [48 39 81]
 [48 39 81]
 [48 39 81]]


In [ ]:
r1 = np.repeat(climate_data,3,axis=1) #axis implies 0 is rows mei multiply by that num or 1 implies column mei multiply by number and so on as dim increases
print(r1)

[[73 73 73 41 41 41 32 32 32]
 [34 34 34 54 54 54 22 22 22]
 [36 36 36 76 76 76 54 54 54]
 [48 48 48 39 39 39 81 81 81]]


In [ ]:
arr = np.ones((5,5), dtype="int16")
for i in range(1,4):
    if i!=2:
        arr[i,1:4] = [0,0,0]
    elif i==2:
        arr[i,1:4] = [0,9,0]
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#another method

arr = np.ones((5,5), dtype="int8")
z = np.zeros((3,3), dtype="int8")
z[1,1] = 9

arr[1:4,1:4] = z
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


####BE CAREFUL AS YOU COPY ARRAY

In [14]:
a = np.array([1,2,3])
b = a #this changes pointer not copies
#eg
#b[0] = 100
print(b)
print(a)


[1 2 3]
[1 2 3]


In [ ]:
#moving on from shallow copy

b = a.copy()
b[0] = 100

print(b,"\n",a)

[100   2   3] 
 [1 2 3]


Mathematics

In [ ]:
a = np.array([1,2,4,5])
#element wise operators

print(a+2,a-2,a*3,a/2)

[3 4 6 7] [-1  0  2  3] [ 3  6 12 15] [0.5 1.  2.  2.5]


In [ ]:
b = [1,2,4,2]

print(a+b)

[2 4 8 7]


In [ ]:
#exponents

a**2

array([ 1,  4, 16, 25])

In [ ]:
#operators
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.65364362  0.28366219]


Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)


print(np.matmul(a,b))
print(np.dot(a,b))

#rules apply!

[[1. 1. 1.]
 [1. 1. 1.]]
[[6. 6.]
 [6. 6.]]
[[6. 6.]
 [6. 6.]]


In [ ]:
#Finding determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [ ]:
 #this won't work
 np.det(c)

1.0

####Statistics


In [ ]:
#Trying out min mean and max or mode and median
stats = np.array([[1,2,3],[3,4,5]])
np.min(stats)


1

In [ ]:
np.min(stats, axis=1) #runs on columns
np.min(stats, axis=0) #runs on rows

array([1, 3])

In [ ]:
np.max(stats)

5

In [ ]:
np.sum(stats)
#gives sum of all elements

18

Reorganising Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print()
print()
after = before.reshape((2,2,2))
print(after)

#the number of elements in reshaped and previous element must be same

[[1 2 3 4]
 [5 6 7 8]]


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stacking Vertically Vectors

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
#Horizontal Stack
h1 = np.zeros((2,4))
h2 = np.ones((2,2))
np.hstack((h1,h2))

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

Loading File Into Numpy For Evaluation

In [ ]:
filedata = np.genfromtxt('Data.txt',delimiter=',')
filedata_2 = filedata.astype('int32')
print(filedata_2)

[[1 2 3 4]
 [5 6 7 8]
 [9 6 7 2]]


##Boolean Masking and Advanced Indexing

In [ ]:
filedata>50
filedata>2 #gives boolean value as to where value is greater than 2 and where its false

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [ ]:
#But if we use this format we can get those elements>2
filedata_2[filedata_2>2]

array([3, 4, 5, 6, 7, 8, 9, 6, 7], dtype=int32)

In [ ]:
#You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

#so passed in a list and it indexed all values based index in the list but ya the index must contain


array([2, 3, 9])

In [ ]:
np.any(filedata_2>2,axis=0) #0 means column and any means that atleast oneelement is greater than given number
#1 means columns and all means that all elements need to be>2

array([ True,  True,  True,  True])

In [ ]:
np.all(filedata_2>2,axis=1)

array([False,  True, False])

In [ ]:
#operators work!
filedata_2[((filedata_2>2) & (filedata_2<8))]

array([3, 4, 5, 6, 7, 6, 7], dtype=int32)